name: Windows unit tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:

  build-and-test:
    name: unit-win
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        # Selected python versions only
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v3

      - name: Configure Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install
        run: |
          python setup.py build

      - name: Run unit tests
        run: |
          python test.py

