name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - name: Configure Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        #with:
          #cache: 'pip'
          #cache-dependency-path: setup.py

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.13.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
